"""
File Generator — creates downloadable Excel and PDF reports from data
Used by API Agent and Workflow Agent to return formatted reports

Dependencies: openpyxl (Excel), reportlab (PDF) — optional, graceful fallback
"""
import os
import json
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "reports")


def _ensure_reports_dir():
    os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_excel(data: list[dict], title: str = "Report",
                    filename: str = None) -> str:
    """
    Generate an Excel file from a list of dicts.
    Returns the file path, or empty string if openpyxl not installed.
    """
    _ensure_reports_dir()

    if not filename:
        filename = f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"

    filepath = os.path.join(REPORTS_DIR, filename)

    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment

        wb = Workbook()
        ws = wb.active
        ws.title = title[:31]  # Excel limit

        # Header styling
        header_font = Font(bold=True, color="FFFFFF", size=11)
        header_fill = PatternFill(start_color="003366", end_color="003366", fill_type="solid")

        if not data:
            ws.append(["No data available"])
            wb.save(filepath)
            return filepath

        # Write headers
        headers = list(data[0].keys())
        for col_idx, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col_idx, value=header.replace("_", " ").title())
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")

        # Write data rows
        for row_idx, row_data in enumerate(data, 2):
            for col_idx, header in enumerate(headers, 1):
                ws.cell(row=row_idx, column=col_idx, value=row_data.get(header, ""))

        # Auto-fit column widths
        for col_idx, header in enumerate(headers, 1):
            max_len = max(len(str(header)), *(len(str(row.get(header, ""))) for row in data))
            ws.column_dimensions[chr(64 + col_idx) if col_idx <= 26 else "AA"].width = min(max_len + 4, 40)

        wb.save(filepath)
        logger.info(f"Excel report generated: {filepath}")
        return filepath

    except ImportError:
        logger.warning("openpyxl not installed — saving as CSV instead")
        csv_path = filepath.replace(".xlsx", ".csv")
        import csv
        with open(csv_path, 'w', newline='') as f:
            if data:
                writer = csv.DictWriter(f, fieldnames=data[0].keys())
                writer.writeheader()
                writer.writerows(data)
        return csv_path


def generate_pdf(content: str, title: str = "Report",
                  filename: str = None) -> str:
    """
    Generate a simple PDF report from text content.
    Returns file path, or empty string if reportlab not installed.
    """
    _ensure_reports_dir()

    if not filename:
        filename = f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    filepath = os.path.join(REPORTS_DIR, filename)

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

        doc = SimpleDocTemplate(filepath, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Title
        story.append(Paragraph(title, styles['Title']))
        story.append(Spacer(1, 20))

        # Content (split by newline for paragraphs)
        for line in content.split('\n'):
            if line.strip():
                story.append(Paragraph(line, styles['Normal']))
                story.append(Spacer(1, 6))

        # Footer
        story.append(Spacer(1, 30))
        story.append(Paragraph(
            f"Generated by KPMG PMO AI Chatbot — {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            styles['Italic']
        ))

        doc.build(story)
        logger.info(f"PDF report generated: {filepath}")
        return filepath

    except ImportError:
        logger.warning("reportlab not installed — saving as .txt instead")
        txt_path = filepath.replace(".pdf", ".txt")
        with open(txt_path, 'w') as f:
            f.write(f"{title}\n{'='*len(title)}\n\n{content}")
        return txt_path
